### ISSUE TITLE
Motivation of writing in JS [question]

### ISSUE THREAD

**Issue by navaru** [gtlbupt/node-rtmp#1]
I am a Node.js developer and was curious why did you choose to write a JS version instead of using simple-rtmp-server

Great effort, btw!

**Comment by gtlbupt** [comment]
I was inspered by https://github.com/felixge/faster-than-c  .
1.  I want to see whether  RTMP Server can be implemented by pure NodeJS， not by c++ binding.
2.  I do  live-broadcast using rtmp protocol now and I use NodeJS as my major  language .  Nodejs does have a RTMP library so I have to write one .
